- README.md
- lib/pom.xml
- tkltest/generate/generate.py
Updated library dependency versions flagged with vulnerability warnings
Tested locally using CI test cases
> Component version updates

- .github/workflows/python_test.yml
- Dockerfile
- README.md
- docker-compose.yml
- lib/download_lib_jars.sh
- lib/settings.xml
- test/test_cli_docker.bats
Enabled support for running CLI via docker or docker compose
Related to #30 
Created test cases that run the CLI via docker-compose. These tests will run in CI.
> Issue30 dockerize cli

- Dockerfile
- README.md
- Updated dockerfile to run maven commands directly instead of calling the download script (which caused issues on windows)
- Updated installation instructions in readme
> Docker and readme updates

- tkltest/generate/generate.py
Correct the extender process error handling 
Related to # (48)
> issue #48 correct error handling for Popen

- tkltest/execute/execute.py
- tkltest/util/build_util.py
1. Fix maven system scope dependency entries that are specified as folders by jarring them 2. Remove redundant entry from randoop/evosuite standalone maven build file.
Related to # (52)
> Issue 52 maven script

- tkltest/util/build_util.py
Handle case where last entry of classpath file doesn't end with a newline
> handle case where last line in classpath file doesn't end with a newline

- README.md
- test/test_cli_irs.bats
- tkltest/generate/generate.py
This PR implements a thread-based solution to catch extender failures by the cli
> Cli catch extender exceptions

- tkltest/generate/generate.py
Change the termination mechanism in case of extender error to use a signal between the running thread and the main process.
Related to #74 
> use a signal to indicate extender failure

- tkltest/generate/generate.py
Replace deprecated method for checking if thread is alive with a newer version. 
> change is alive method name

- tkltest/generate/generate.py
Set JVM max heap size to 2G for all calls to testgen core components (CTD modeler, sequence initializer, sequence extender)
> JVM heap size update

- tkltest/generate/augment.py
- tkltest/generate/generate.py
- tkltest/util/coverage_util.py
Perform test augmentation by selecting the initial (base) test suite based on coverage efficiency of the CTD and evosuite test suites
Related to #70 
Tested locally using CI tests and additional input apps.
> Issue70 coverage augmentation

- tkltest/util/build_util.py
Ignore empty lines in classpath file
> bug fix - ignore empty lines in classpath file

- .github/workflows/release.yml
- .github/workflows/release_config.json
Workflow for automatically publishing CLI releases
> Workflow for release automation

- test/test_generate_execute.py
- tkltest/execute/execute.py
- tkltest/generate/augment.py
- tkltest/util/build_util.py
- tkltest/util/coverage_util.py
Make offline instrumentation work in maven build file forour  automatically generated tests
Related to #109
> Support offline instrumentation in maven

- .github/workflows/release.yml
- .github/workflows/release_config.json
Recover release automation workflow files deleted by PR https://github.com/konveyor/tackle-test-generator-cli/pull/125
Please include a summary of the change and the issue that the PR is related to.
Please also include relevant motivation and context.
List any dependencies that are required for this change.
> recover release automation workflow

- .github/workflows/release.yml
Added release workflow steps for publishing tackle-test container images to GitHub container registry. The published
image is tagged with the release version.
Related to #90 
> Publish tkltest docker image to GitHub container registry on release

- README.md
- tkltest/tkltest.py
- tkltest/util/config_options.py
- tkltest/util/config_util.py
Updates to config options processing to handle `dev_tests` options as "non-command" options
Tested using CI test cases
> Handling of non-command configuration options

- tkltest/generate/unit/augment.py
replace copy with move:
at the beginning of augmentation, we move the ctd directory to backup.
so we build each EVS file with out the CTD
Related to # 153
- [x ] Bug fix (non-breaking change that fixes an issue)
tested on PDL app, with all relevant options 
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] New and existing tests pass locally with my changes
- [x ] Any dependent changes have been merged and published …
> Improve performance of augmentation

- tkltest/util/coverage_util.py
--classpath was not used correctly in case of a list of classpathes
Related to # 157
splitnJoin Tests
- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] New and existing tests pass locally with my changes
- [X ] Any dependent changes have been merged and published in downstream modules
> fix opt creation for jacococli

- test/data/windup-sample/migration-sample-app-master/pom.xml
- test/data/windup-sample/migration-sample-app-master/simple-sample-services/pom.xml
- test/data/windup-sample/windup-sample-webMonoClasspath.txt
The test app from Windup contained vulnerable log4j dependency, declared in its `pom.xml` files.
The dependency was replaced by log4j-2 jars, in their newest version.
The maven unit test of `tkltest-unit` was updated accordingly.
The windup app compiles.
> Changed app dependency to the newest versions

- test/data/14_spark/tkltest_config.toml
- test/data/3_scribe-java/tkltest_config.toml
- test/data/windup-sample/tkltest_config_web.toml
- test/unit/test_cli.bats
- test/unit/test_cli_irs.bats
- test/unit/test_generate_execute.py
- tkltest/execute/unit/execute.py
- tkltest/generate/unit/generate.py
- tkltest/util/config_options_unit.py
- tkltest/util/config_util.py
Fixed handling of command-line option for disabling augmentation; renamed option to reflect its semantics
Related to #162
Tested using updated CI test cases
> Fix handling of command-line option for disabling augmentation

- .github/workflows/tkltest_ui_ci.yml
- .gitmodules
- setup.py
- test/ui/test_cli.bats
- test/ui/tkltest_ui_config.toml
- test/unit/test_cli.bats
- test/unit/test_config.py
- test/unit/test_unit_tests.py
- tkltest/tkltest.py
- tkltest/tkltest_ui.py
- tkltest/tkltest_unit.py
- tkltest/util/config_options.py
- tkltest/util/config_options_ui.py
- tkltest/util/config_options_unit.py
- tkltest/util/config_util.py
- Added tkltest-ui command for supporting UI-level test generation
- Created initial version of configuration option specification for UI test generation. The spec is split into
normal options (that are documented and available to end-users) and "internal" options that are meant
for experimentation and advanced use (tool users would typically not have any need of using these options).
- Added CI workflow and initial set to CLI tests for tkltest-ui.
> Tkltest UI command and configuration options (initial version)

- lib/pom.xml
- tkltest/generate/unit/generate.py
- tkltest/util/constants.py
Updated core jar dependency to use the new unit jar and v1.1.0.
Core updates integrated by this PR:
- Avoid adding assertions on argumentless constructors (https://github.com/konveyor/tackle-test-generator-core/pull/118)
- Create assertions on receiver objects when return type of invoked method is void (https://github.com/konveyor/tackle-test-generator-core/pull/120)
- Avoid adding assertions on constructors of primitive wrapper types (https://github.com/konveyor/tackle-test-generator-core/pull/122)
> Integrate core updates for refinements in assertion generation 

- .gitmodules
- lib/pom.xml
- requirements.txt
- setup.py
- test/ui/data/petclinic/tkltest_ui_config.toml
- test/ui/test_cli.bats
- tkltest/generate/ui/generate.py
- tkltest/tkltest_ui.py
- tkltest/util/constants.py
- tkltest/util/ui/config_options_ui.py
- Initial implementation of the tkltest-ui generate command which calls the crawljax runner from the core repo UI module
- Test data webapps set up as a git submodule
- Configuration for the petclinic app
- Updated bats test for the tkltest-ui command
> Tkltest UI generate command

- .github/workflows/release.yml
- .github/workflows/tkltest_unit_ci.yml
- Dockerfile
Updates to processing of settings.xml in CI workflow and dockerfile
> CI workflow fix

- Dockerfile
- README.md
- test/test_cli_docker.bats
- Updated gradle version (v7.4) installed in docker
- CI tests for build types maven and gradle to be run on the dockerized cli
- Updated README instructions 
Tested using existing and new CI tests
> Docker gradle update and new CI tests for dockerized CLI

- test/ui/test_cli_generate.bats
- tkltest/generate/ui/generate.py
Fixed output dir path to be consistent with core update (of not moving crawl dir one level up in the dir structure)
> Test output dir path fix

- tkltest/execute/ui/execute.py
- tkltest/generate/ui/generate.py
- tkltest/util/ui/browser_util.py
Moved browser cleanup code to new browser util module; added browser cleanup step to execute command
> Browser cleanup after test execution

- .github/workflows/tkltest_ui_ci.yml
- test/ui/data/addressbook/deploy_app.sh
- test/ui/data/addressbook/tkltest_ui_config.toml
- test/ui/data/addressbook/tkltest_ui_formdata_config.toml
- test/ui/test_cli_addressbook.bats
- Configuration files for a new webapp, addressbook, to be used for CI testing of tkltest-ui
- Bats test case for the webapp
- CI workflow update for running the bats test
>  Addressbook webapp for CI testing of tkltest-ui

- Dockerfile
- README.md
- entrypoint.sh
- test/test_cli_docker.bats
- A new entrypoint script that supports tkltest-unit/ui commands and restricts other commands from being executed in the CLI container
- Related updates to dockerfile, docker unit tests, and readme
> Update docker image to support both tkltest-unit and tkltest-ui commands

- tkltest/generate/unit/generate.py
- tkltest/generate/unit/generate_standalone.py
support spaces in classpathRelated to # 87
on ctd-amplified, evosuite, randoop
> Support spaces in classpath

- test/ui/test_cli_addressbook.bats
- test/ui/test_cli_petclinic.bats
- tkltest/generate/ui/generate_selenium.py
- tkltest/generate/ui/templates/GeneratedTests.jinja
- Updates in Selenium test generation to use conditional waits from Selenium API in the generated test code
- CI executions of generated tests for both API types for petclinic and addressbook webapps
> Selenium API test expected conditions wait

- .github/workflows/tkltest_ui_ci.yml
- Dockerfile
- docker-compose.yml
- test/ui/test_cli.bats
- test/ui/test_cli_addressbook.bats
- test/ui/test_cli_docker.bats
- test/ui/test_cli_docker_addressbook.bats
- test/ui/test_cli_docker_petclinic.bats
- test/ui/test_cli_petclinic.bats
- tkltest/generate/ui/generate_selenium.py
- Updates to dockerfile to install chrome and other prerequisites required for UI test generation/execution
- Updates to docker-compose to use host network mode so that AUT webapp deployed on the host machine can be accessed in the container
- Bats test cases for running tkltest-ui in docker (for petclinic and addressbook webapps)
Testing using new and existing CI test cases
> Tkltest UI docker tests

- .gitattributes
- .github/workflows/tkltest_ui_ci.yml
- .github/workflows/tkltest_unit_ci.yml
This PR adds `.gitattributes` file with eol settings, and updates to CI workflows to ignore gitattributes updates.
Tested using CI test cases
> add gitattributes file 

- .github/workflows/tkltest_unit_ci.yml
- README.md
- Updated instruction for getting sample webapps with link to the external repo
- updated prereq step for unit CI workflow to avoid failure while installing libxml2-utils
> Readme and unit CI install step updates

- tkltest/util/unit/build_util.py
removing unnecessary jars from the build files
Please include a summary of the change and the issue that the PR is related to.
Please also include relevant motivation and context.
List any dependencies that are required for this change.
Related to # 101
on gradle, maven and ant, both online and offline instrumentation
> clean classpath of build files

- tkltest/execute/unit/execute.py
- tkltest/tkltest_unit.py
continue running when execution of one module fails
Related to # 97
> skip failed modules

- tkltest/util/unit/build_util.py
a jar was missing for execution
Please include a summary of the change and the issue that the PR is related to.
Please also include relevant motivation and context.
List any dependencies that are required for this change.
> adding missing jar

- Dockerfile
Download evosuite jars from their new location with dockerfile, fix contributed by @sirhczac1
> download evosuite jars with Dockerfile

- doc/ui/user_guide.md
- doc/unit/user_guide.md
`tkltest-unit` and `tkltest-ui` `generate` and `execute` commands produce various output artifacts. We added a section to the respective user guides to describe these artifacts in an organized way.
> Document the output artifacts of tkltest-unit and tkltest-ui commands 

- test/ui/data/addressbook/tkltest_ui_config.toml
- test/ui/data/petclinic/tkltest_ui_config.toml
- test/ui/tkltest_ui_config.toml
Removed unsupported option "add_state_diff_assertions" from test config files
> Test config file cleanup

- tkltest/generate/unit/generate.py
Fix the way the temporary test directory is renamed to the final one, to avoid permission errors
> Fix rename of temporary test directory

- tkltest/util/constants.py
- tkltest/util/unit/build_util.py
for user build file, instead of using jars from the lib files, we take it from repository.
Please include a summary of the change and the issue that the PR is related to.
Please also include relevant motivation and context.
List any dependencies that are required for this change.
Related to #123
tested on both gradle and maven user build files
> Use central repository for defining test dependencies when integrating tests into app build file

- .github/workflows/tkltest_ui_ci.yml
- .github/workflows/tkltest_unit_ci.yml
- Dockerfile
- doc/installation.md
- tkltest/util/constants.py
> Support python 3.9

- .github/workflows/release.yml
Fix refactored lib folder name in release yml
> fix lib folder name

- requirements.txt
- setup.py
nltk security requirement for 3.6.6 isn't compatible with Windows distribution of 3.7, hence refined the requirement to 3.6.6 or above
> Allow nltk versions greater than 3.6.6 for compatibility with Windows

- .github/workflows/tkltest_unit_ci.yml
Updated tkltest-unit CI workflow to use Gradle 7.4
> CI failure caused by gradle version

- tkltest/generate/ui/templates/GeneratedTests.jinja
Updated Selenium API test template to add Chrome option for ignoring certificate errors
> Ignore certificate errors during test execution

- test/ui/data/petclinic/tkltest_ui_config.toml
- tkltest/util/ui/config_options_ui.py
This PR updates the default value for max depth config option, and updates the petclinic config to use unlimited states and crawl depth.
> Updates related to unlimited crawl depth support

- tkltest/generate/ui/heuristic_labels.py
Added fix for table header issue
Related to # (157) in planning repo
> Fix for none deref 

- test/ui/heuristic_labels_test.py
- tkltest/generate/ui/generate_with_labels_analysis.py
- tkltest/generate/ui/heuristic_labels.py
- tkltest/generate/ui/ranked_attributes.json
This PR is to improve method-level labels as well as refactor the code for form field and element level labels. There are also a few changes to improve form field and element level labels. It also fixes 2 of the issues during generation that had been logged.
- [+] Bug fix (non-breaking change that fixes an issue)
- [+] New feature (non-breaking change that adds functionality)
- [+] Refactoring (non-breaking code restructuring that preserves functionality)
test/ui/heuristic_labels_test.py has been modified to check the latest version of the code.
- [+] My code follows the style guidelines of this project
- [+] I have performed a self-review of my own code
- [+] I have commented my code, particularly in hard-to-understand areas
- [+] I …
> Improved method labels and refactored code

- test/ui/data/petclinic/tkltest_ui_precrawl_actions_config.toml
- tkltest/generate/ui/generate_selenium.py
Add precrawl action for accepting alerts
Related to # (161) in planning repo
> Add precrawl action for accepting alerts

- tkltest/generate/ui/generate_selenium.py
- tkltest/generate/ui/generate_with_labels_analysis.py
- tkltest/generate/ui/heuristic_labels.py
Fix decoding issue when reading crawl paths
Related to # (158) in planning repo
> Fix for decoding issue

- doc/ui/tkltest_ui_config_options.md
Update documentation for dont_click.children_of and form clarification
Related to # (163) in planning repo
> Update documentation for dont_click.children_of and form clarification

- test/ui/heuristic_labels_test.py
- tkltest/generate/ui/heuristic_labels.py
This PR adds a fix for the check on unique eventables as a part of the method level summary computation.
- [+] Bug fix (non-breaking change that fixes an issue)
- [+] My code follows the style guidelines of this project
- [+] I have performed a self-review of my own code
- [+] I have commented my code, particularly in hard-to-understand areas
- [+] I have made corresponding changes to the documentation
- [+] I have added tests that prove my fix is effective or that my feature works
- [+] New and existing tests pass locally with my changes
- [+] Any dependent …
> Unique eventables fix

- test/unit/test_unit_tests.py
- tkltest/util/unit/build_util.py
change the location of tkltest_pom.xml
Related to # (issue) 165
tests was changed accordingly 
> Issue 165 changes for integration into tackle hub

- README.md
Add link to CoC in readme page
> Add link to CoC in readme page

- tkltest-lib/pom.xml
- tkltest/generate/unit/generate.py
- tkltest/util/config_util.py
Fix faster xml jackson vulnerability
> Fix faster xml jackson vulnerability

- .github/workflows/tkltest_ui_ci.yml
- .github/workflows/tkltest_unit_ci.yml
- tkltest/unit/generate/generate.py
handling the case in witch there is no target methods
Related to172
> Issue 172 zero targets

- .github/workflows/tkltest_ui_ci.yml
- .github/workflows/tkltest_unit_ci.yml
Signed-off-by: haim-kermany <haim.kermany@gmail.com>
do not set JAVA_HOME. the JAVA_HOME is set by the set_java action
- [] I have commented my code, particularly in hard-to-understand areas
> do not override java home

- tkltest/unit/generate/generate.py
Wrap target and excluded classes with single quotes in modeling command line, to avoid unix misinterpretation of special characters such as $ that occurs in inner classes.
Related to # (175) in planning repo
> Inner class inclusion fix

- setup.py
- tkltest/ui/generate/templates/GeneratedTests.jinja
Updated UI test template to set chrome option to handle chromedriver 111 issue during execution of the generated tests.
> Chromedriver patch for test execution

- setup.py
This PR updates beautiful soup dependency
> Dependency update

- .github/workflows/tkltest_unit_ci.yml
- setup/tkltestunit.Dockerfile
- test/unit/test_generate_execute.py
Fix for unit test generator docker build failure: changed base maven image and updated python installation.
The PR also contains updates to the unit test generator CI to selectively install dependencies and update to two flaky unit tests to use evosuite as the base generator.
Related to #334 
> Issue334 docker fix

- .github/workflows/tkltest_ui_ci.yml
- setup.py
- setup/tkltestui.Dockerfile
- setup/tkltestui.setup.py
- tkltest/ui/generate/generate_selenium.py
This PR disables UI test labeling and contains related updates to setup/build files and CI workflow.
> Disable UI test labeling

- .github/workflows/release.yml
This PR contains updates to the release workflow:
- Add step for freeing up disk space on ubuntu runner
- Enable publishing of tkltest-ui docker image
- Update action versions
- Replace deprecated use of `set-output` command
> Release workflow updates and fixes
